const mongoose = require("mongoose");

const MONGO_URI = "mongodb://imtiasif1:pzpUMbcC62RQIRSx@ac-exhfwpp-shard-00-00.iamyzis.mongodb.net:27017,ac-exhfwpp-shard-00-01.iamyzis.mongodb.net:27017,ac-exhfwpp-shard-00-02.iamyzis.mongodb.net:27017/?ssl=true&replicaSet=atlas-121uts-shard-0&authSource=admin&appName=Cluster0";

// ================= SCHEMA =================
const outfitSchema = new mongoose.Schema({
  name: { type: String, required: true },
  type: { type: String, required: true },
  category: { type: String, required: true },
  gender: { type: String, required: true },
  color: { type: [String], required: true },
  url: { type: String, required: true },
  imageUrl: { type: String, required: true },
  brand: { type: String, required: true },
  price: { type: Number, default: null },
}, { timestamps: true });

// CATEGORY FLOW
outfitSchema.index({gender: 1,category: 1,type: 1,color: 1,brand: 1});
// BRAND FLOW
outfitSchema.index({brand: 1,gender: 1, type: 1, color: 1});

const Outfit = mongoose.model("Outfit", outfitSchema);

// ================= DATA =================
const outfits = [
  {
    name: "Blue Dobby Embroided Kurta",
    type: "Kurta",
    category: "Casual",
    gender: "Female",
    color: ["Blue"],
    url: "https://www.junaidjamshed.com/blue-dobby-embroidered-kurti-jss26606s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/s/jss-26-606_6_.jpg",
    brand: "Junaid Jamshed",
    price: 5990,
  },
  {
    name: "White Blended Kurta",
    type: "Kurta",
    category: "Casual",
    gender: "Male",
    color: ["White"],
    url: "https://bonanzasatrangi.com/products/m25kus1002",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/M25KUS1002_01.jpg?v=1755802011&width=600",
    brand: "Bonanza Satrangi",
    price: 2928,
  },
  {
    name: "Purple Blended Kurta",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Purple"],
    url: "https://bonanzasatrangi.com/products/mp1pbw25bm11d1",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/052A0057_0d05d5a2-17b2-4b9a-add9-f1f2bab68628.jpg?v=1770030106&width=600",
    brand: "Bonanza Satrangi",
    price: 3192,
  },
  {
    name: "Black Blended Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Male",
    color: ["Black"],
    url: "http://bonanzasatrangi.com/collections/men/products/mps25sse2055",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/052A9301.jpg?v=1758018588&width=600",
    brand: "Bonanza Satrangi",
    price: 5934,
  },
  {
    name: "Brown Blended Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Male",
    color: ["Brown"],
    url: "https://bonanzasatrangi.com/collections/men/products/mps25sse2050",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/052A4468_f69da1a9-9ee3-418f-af75-75fd46e981c1.jpg?v=1755801777&width=600",
    brand: "Bonanza Satrangi",
    price: 6923,
  },
  {
    name: "Green Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Green"],
    url: "https://bonanzasatrangi.com/collections/men/products/mu2pbw25o11d1",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/MU2PBW25O11D1_2.jpg?v=1769087896&width=600",
    brand: "Bonanza Satrangi",
    price: 4268,
  },

  // ================= DINERS =================
  {
    name: "Coffee Brown Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Brown"],
    url: "https://diners.com.pk/products/ga3984-c-brown",
    imageUrl: "https://diners.com.pk/cdn/shop/files/GA3984CBROWNRS7490-01_2000x.webp?v=1721480637",
    brand: "Diners",
    price: 5383,
  },
  {
    name: "Royal Blue Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://diners.com.pk/products/waistcoat-for-men-107",
    imageUrl: "https://diners.com.pk/cdn/shop/products/GA-3670-R-BLUE-RS-5690-02_2000x.jpg?v=1686072211",
    brand: "Diners",
    price: 4088,
  },
  {
    name: "Blue Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://diners.com.pk/products/ga4045-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/GA4045-Blue-01_2000x.webp?v=1743160385",
    brand: "Diners",
    price: 6690,
  },
  {
    name: "Blue Check Blazer",
    type: "Blazer",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://diners.com.pk/products/ca4025-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/CA4025-BLUE-02_2000x.webp?v=1776341219",
    brand: "Diners",
    price: 17493,
  },
  {
    name: "Olive Green Textured Blazer",
    type: "Blazer",
    category: "Formal",
    gender: "Male",
    color: ["Green"],
    url: "https://diners.com.pk/products/ca4070-green",
    imageUrl: "https://diners.com.pk/cdn/shop/files/CA4070-GREEN-01_2000x.webp?v=1774952146",
    brand: "Diners",
    price: 19992,
  },

  // ================= JUNAID JAMSHED =================
  {
    name: "Black Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Black"],
    url: "https://www.junaidjamshed.com/black-waistcoat-jjvca33763.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/j/jjvc-33763_2_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 8990,
  },
  {
    name: "Gold Formal Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Gold"],
    url: "https://www.junaidjamshed.com/gold-formal-waistcoat-jjvca50358.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/5/0/50358jjvc_1_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 11990,
  },
  {
    name: "Maroon Formal Kurta",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Maroon"],
    url: "https://www.junaidjamshed.com/maroon-formal-kurta-jjkspa48296.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/4/8/48296jjksp_1_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 16990,
  },
  {
    name: "Mustard Formal Kurta",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Gold"],
    url: "https://www.junaidjamshed.com/mustard-formal-kurta-jjkspa50483.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/5/0/50483jjksp_1_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 9990,
  },
  {
    name: "Black Semi Formal Kameez Shalwar",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Male",
    color: ["Black"],
    url: "https://www.junaidjamshed.com/black-semi-formal-kameez-shalwar-jjksa60006.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/6/0/60006jjks_1_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: null,
  },

  // ================= OMAL BY KOMAL =================
  {
    name: "Kurta and Dupatta",
    type: "Kurta",
    category: "Casual",
    gender: "Female",
    color: ["White"],
    url: "https://omalbykomal.com/collections/rang-e-azadi/products/sehar",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/IMG_7299.jpg?v=1755435533&width=800",
    brand: "Omal by Komal",
    price: 7150,
  },
  {
    name: "Maroon Saree",
    type: "Saree",
    category: "Formal",
    gender: "Female",
    color: ["Purple"],
    url: "https://omalbykomal.com/collections/saaree-edit-24/products/dilawiz",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/98P09870_2-min.jpg?v=1755435617&width=800",
    brand: "Omal by Komal",
    price: 6500,
  },
  {
    name: "Purple Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Purple"],
    url: "https://omalbykomal.com/products/naaz-3pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/Picsart_25-09-17_13-21-00-027.jpg?v=1758267628&width=800",
    brand: "Omal by Komal",
    price: 7750,
  },
  {
    name: "Green Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Green"],
    url: "https://omalbykomal.com/products/amber-3pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/DSC05492.jpg?v=1766938636&width=800",
    brand: "Omal by Komal",
    price: 8150,
  },
  {
    name: "Maroon Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Maroon"],
    url: "https://omalbykomal.com/collections/sardiyon-ki-shaam/products/sareena-2pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/rn-image_picker_lib_temp_a1db346e-2e89-44ce-8010-8a975151e1ba.jpg?v=1767601457&width=800",
    brand: "Omal by Komal",
    price: 7500,
  },

  // ================= ZELLBURY =================
  {
    name: "Cotton Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Brown"],
    url: "https://zellbury.com/products/comfort-cotton-shalwar-kameez-mskc252631",
    imageUrl: "https://zellbury.com/cdn/shop/files/MSKC252631_5.jpg?v=1770442645&width=990",
    brand: "Zellbury",
    price: 4420,
  },
  {
    name: "Purple Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Purple"],
    url: "https://zellbury.com/products/marvel-shalwar-kameez-mskms252697",
    imageUrl: "https://zellbury.com/cdn/shop/files/MSKMS252697_10.jpg?v=1758089757&width=990",
    brand: "Zellbury",
    price: 4990,
  },
  {
    name: "Wash and Wear Kurta",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://zellbury.com/products/wash-wear-kurta-mkds25007",
    imageUrl: "https://zellbury.com/cdn/shop/files/MKDS25007_9.jpg?v=1755519194&width=990",
    brand: "Zellbury",
    price: 2990,
  },
  {
    name: "Wash and Wear Kurta",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Black"],
    url: "https://zellbury.com/products/wash-wear-kurta-mkj25001",
    imageUrl: "https://zellbury.com/cdn/shop/files/MKJ25001_BLACK_2.jpg?v=1746262248&width=990",
    brand: "Zellbury",
    price: 2690,
  },
  {
    name: "Blue Blazer",
    type: "Blazer",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://zellbury.com/products/blazer-mcb25006",
    imageUrl: "https://zellbury.com/cdn/shop/files/MCB25006_NAVY_8.jpg?v=1759902919&width=1946",
    brand: "Zellbury",
    price: 6990,
  },
    {
    name: "Embroidered Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Yellow"],
    url: "https://zellbury.com/products/shirt-shalwar-dupatta-wuc26e34056",
    imageUrl: "https://zellbury.com/cdn/shop/files/WUC26E34056_6.jpg?v=1775550204&width=823",
    brand: "Zellbury",
    price: 4490,
  },
  {
    name: "Embroidered Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Pink"],
    url: "https://zellbury.com/products/shirt-shalwar-dupatta-wuc26e34048?pr_prod_strat=jac&pr_rec_id=843d136c1&pr_rec_pid=8228516167727&pr_ref_pid=8228516528175&pr_seq=uniform",
    imageUrl: "https://zellbury.com/cdn/shop/files/WUC26E34048_8.jpg?v=1775550202&width=823",
    brand: "Zellbury",
    price: 4490,
  },
  {
    name: "Blue Abaya",
    type: "Abaya",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://zellbury.com/products/abaya-wmw25042",
    imageUrl: "https://zellbury.com/cdn/shop/files/WMW25042_2.jpg?v=1772604258&width=823",
    brand: "Zellbury",
    price: 3290,
  },
  {
    name: "Blue Abaya",
    type: "Abaya",
    category: "Casual",
    gender: "Female",
    color: ["Blue"],
    url: "https://zellbury.com/products/abaya-wmw25037",
    imageUrl: "https://zellbury.com/cdn/shop/files/WMW25037_1.jpg?v=1772604259&width=823",
    brand: "Zellbury",
    price: 3290,
  },
  {
    name: "Marvel Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Blue"],
    url: "https://zellbury.com/products/marvel-shalwar-kameez-mskm2526111",
    imageUrl: "https://zellbury.com/cdn/shop/files/MSKM2526111_3.jpg?v=1755519256&width=823",
    brand: "Zellbury",
    price: 4490,
  },
  {
    name: "Black Blazer",
    type: "Blazer",
    category: "Formal",
    gender: "Male",
    color: ["Black"],
    url: "https://zellbury.com/products/blazer-mcbc2506",
    imageUrl: "https://zellbury.com/cdn/shop/files/MCBC2506_NAVY_6.jpg?v=1767696031&width=823",
    brand: "Zellbury",
    price: 7990,
  },

  // ================= JUNAID JAMSHED =================
  {
    name: "Grey Suiting Waistcoat",
    type: "Waistcoat",
    category: "Casual",
    gender: "Male",
    color: ["Grey"],
    url: "https://www.junaidjamshed.com/grey-suiting-waistcoat-jjvca33742.html",
    imageUrl: "https://zellbury.com/cdn/shop/files/MCBC2506_NAVY_6.jpg?v=1767696031&width=823",
    brand: "Junaid Jamshed",
    price: 11990,
  },
  {
    name: "Brown Waistcoat",
    type: "Waistcoat",
    category: "Casual",
    gender: "Male",
    color: ["Brown"],
    url: "https://www.junaidjamshed.com/brown-waistcoat-jjvca33757.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/4/7/47702_3__8.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 8990,
  },
  {
    name: "Green Cotton Plain Kameez Shalwar",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Green"],
    url: "https://www.junaidjamshed.com/green-cotton-plain-kameez-shalwar-jjksa60080.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/j/jjks-60080_2_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 8490,
  },
  {
    name: "Light Brown Georgette Abaya",
    type: "Abaya",
    category: "Modest",
    gender: "Female",
    color: ["Brown"],
    url: "https://www.junaidjamshed.com/light-brown-georgette-abaya-jjab-22-049.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/j/jjab-22-049_2_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 15270,
  },
  {
    name: "Multicolor Lawn Embroidered Stitched 3PC",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Beige"],
    url: "https://www.junaidjamshed.com/multicolor-lawn-embroidered-stitched-3pc-jls26615s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/l/jls-26-615_4_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 9490,
  },
  {
    name: "Multicolor Lawn Printed Unstitched 3PC",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Black"],
    url: "https://www.junaidjamshed.com/multicolor-lawn-embroidered-stitched-3pc-jls26615s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/2/6/26-3878_1_.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 4490,
  },

  // ================= OMAL BY KOMAL =================
  {
    name: "Blue Saree",
    type: "Saree",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://omalbykomal.com/collections/saaree-edit-24/products/saahil",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/98P09574_1_-min.jpg?v=1755435616&width=800",
    brand: "Omal by Komal",
    price: 6500,
  },
  {
    name: "Maroon Saree",
    type: "Saree",
    category: "Formal",
    gender: "Female",
    color: ["Maroon"],
    url: "https://omalbykomal.com/products/ulfat",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/DSC09780_1_-min.jpg?v=1755435612&width=120",
    brand: "Omal by Komal",
    price: 7500,
  },
  {
    name: "Pink Frock - Mahru",
    type: "Frock",
    category: "Festive",
    gender: "Female",
    color: ["Pink"],
    url: "https://omalbykomal.com/collections/eid-edit26/products/mahru-3pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/NRW03056.jpg?v=1772134499&width=800",
    brand: "Omal by Komal",
    price: 9200,
  },
  {
    name: "Pink Frock - Gul - 3Pc",
    type: "Frock",
    category: "Festive",
    gender: "Female",
    color: ["Pink"],
    url: "https://omalbykomal.com/collections/eid-edit26/products/gul-3pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/WhatsApp_Image_2026-03-25_at_10.53.07_AM.jpg?v=1774422548&width=800",
    brand: "Omal by Komal",
    price: 9350,
  },

  // ================= DINERS =================
  {
    name: "Fawn Cotton Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Male",
    color: ["Beige"],
    url: "https://diners.com.pk/products/eg3728-fawn",
    imageUrl: "https://diners.com.pk/cdn/shop/files/EG3728-FAWN-02_47893287-2a71-4511-9809-23f9c01f416e_1200x.webp?v=1772693140",
    brand: "Diners",
    price: 9990,
  },
  {
    name: "Burgundy Wash & Wear Kurta Pajama",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Brown"],
    url: "https://diners.com.pk/products/etkp0052-bargundi",
    imageUrl: "https://diners.com.pk/cdn/shop/files/ETKP0052-BURGUNDY-02_1200x.webp?v=1771573391",
    brand: "Diners",
    price: 14990,
  },
  {
    name: "Printed Unstitched 3PC",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://diners.com.pk/products/wu32144-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/WU32144-BLUE_2_0fe87320-6f3d-4884-9d42-4930e72e443d_1200x.webp?v=1775728465",
    brand: "Diners",
    price: 2990,
  },
  {
    name: "Waistcoat Blue",
    type: "Waistcoat",
    category: "Casual",
    gender: "Male",
    color: ["Blue"],
    url: "https://diners.com.pk/products/ga4048-d-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/GA4048-D-Blue-01_1200x.webp?v=1758718200",
    brand: "Diners",
    price: 7990,
  },

  // ================= BONANZA SATRANGI =================
  {
    name: "Suit - Zariyah - 3 Pc",
    type: "Shalwar Kameez",
    category: "Festive",
    gender: "Female",
    color: ["Blue"],
    url: "https://bonanzasatrangi.com/products/wu3pslw25na10n4",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/WU3PSLW25NA10N4_5.jpg?v=1770968679&width=120",
    brand: "Bonanza Satrangi",
    price: 10590,
  },
  {
    name: "Black Blended Shalwar Suit",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Grey"],
    url: "https://bonanzasatrangi.com/products/mps25kps2051",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/052A5556.jpg?v=1762779115&width=120",
    brand: "Bonanza Satrangi",
    price: 6293,
  },
  {
    name: "Beige Lawn Embroided Kurta",
    type: "Kurta",
    category: "Casual",
    gender: "Female",
    color: ["Beige"],
    url: "https://www.junaidjamshed.com/beige-lawn-embroidered-kurti-jss26602s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/s/jss-26-602_1_.jpg",
    brand: "Junaid Jamshed",
    price: 4490,
  },
  {
    name: "Black Dobby Embroided Stitched 3 Piece",
    type: "Frock",
    category: "Festive",
    gender: "Female",
    color: ["Black"],
    url: "https://www.junaidjamshed.com/black-dobby-embroidered-stitched-3pc-jls26490s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/2/6/26-490s_1_.jpg",
    brand: "Junaid Jamshed",
    price: 12990,
  },
  {
    name: "Pink Cotton Silk Embroided Stitched 3 Piece",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Pink"],
    url: "https://www.junaidjamshed.com/pink-cotton-silk-embroidered-stitched-3pc-jls26553s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/2/6/26-553s_5_.jpg",
    brand: "Junaid Jamshed",
    price: 12990,
  },
  {
    name: "Maroon Crepe Abaya",
    type: "Abaya",
    category: "Modest",
    gender: "Female",
    url: "https://www.junaidjamshed.com/maroon-crepe-abaya-jjab-22-025.html",
    color: ["Maroon"],
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/j/jjab-22-025_1_.jpg",
    brand: "Junaid Jamshed",
    price: 15270,
  },
    {
    name: "Embroidered Kurta Trouser - 2089",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Red"],
    url: "https://zellbury.com/products/kurta-trouser-wps2622089",
    imageUrl: "https://zellbury.com/cdn/shop/files/WPS2622089_1.png?v=1776410500&width=823",
    brand: "Zellbury",
    price: 3890,
  },
  {
    name: "Embroidered Kurta - 2785",
    type: "Kurta",
    category: "Formal",
    gender: "Female",
    color: ["Beige"],
    url: "https://zellbury.com/products/kurta-wps2612785",
    imageUrl: "https://zellbury.com/cdn/shop/files/WPS2612785_1.png?v=1776334244&width=823",
    brand: "Zellbury",
    price: 2190,
  },
  {
    name: "Abaya - 5037",
    type: "Abaya",
    category: "Modest",
    gender: "Female",
    color: ["Brown"],
    url: "https://zellbury.com/products/abaya-wmw25037",
    imageUrl: "https://zellbury.com/cdn/shop/files/WMW25037_1.jpg?v=1772604259&width=823",
    brand: "Zellbury",
    price: 3290,
  },
  {
    name: "Embroidered Shirt Shalwar - 1181",
    type: "Shalwar Kameez",
    category: "Festive",
    gender: "Female",
    color: ["Maroon"],
    url: "https://zellbury.com/products/shirt-shalwar-wus26e21181",
    imageUrl: "https://zellbury.com/cdn/shop/files/WUS26E21181_2_1.jpg?v=1765980237&width=823",
    brand: "Zellbury",
    price: 2990,
  },
  {
    name: "Embroidered Kurta Trouser - 3701",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Purple"],
    url: "https://zellbury.com/products/kurta-trouser-wps2623701",
    imageUrl: "https://zellbury.com/cdn/shop/files/WPS2623701_3.png?v=1776410494&width=823",
    brand: "Zellbury",
    price: 4990,
  },
  {
    name: "Sunaina - 3Pc",
    type: "Frock",
    category: "Formal",
    gender: "Female",
    color: ["Pink"],
    url: "https://omalbykomal.com/collections/mera-eid-ka-jora/products/sunaina-3pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/sunaina1-min.jpg?v=1755435579&width=800",
    brand: "Omal by Komal",
    price: 7500,
  },
  {
    name: "Amber - 3Pc",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Green"],
    url: "https://omalbykomal.com/collections/sardiyon-ki-shaam/products/amber-3pc",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/DSC054981.jpg?v=1765081475&width=800",
    brand: "Omal by Komal",
    price: 8150,
  },
  {
    name: "Raqeeb",
    type: "Saree",
    category: "Festive",
    gender: "Female",
    color: ["Maroon"],
    url: "https://omalbykomal.com/collections/saaree-edit-24/products/raqeeb",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/DSC09915_2_-min.jpg?v=1755435614&width=800",
    brand: "Omal by Komal",
    price: 12500,
  },
  {
    name: "Phool 2PC - Multani Kurta & Dupatta",
    type: "Kurta",
    category: "Casual",
    gender: "Female",
    color: ["Red"],
    url: "https://omalbykomal.com/collections/multani-collection-24/products/phool-multani-kurta-dupatta",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/Phool2_2c5609f5-c974-4657-a3f7-948f390109c6-min.jpg?v=1755435591&width=800",
    brand: "Omal by Komal",
    price: 5400,
  },
  {
    name: "Multicolor Lawn Printed Unstitched 2PC",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Blue"],
    url: "https://www.junaidjamshed.com/multicolor-lawn-printed-unstitched-2pc-jst262403u.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/s/jst-26-2403_2_.jpg",
    brand: "Junaid Jamshed",
    price: 2990,
  },
  {
    name: "Black Dobby Embroidered Kurta",
    type: "Kurta",
    category: "Casual",
    gender: "Female",
    color: ["Black"],
    url: "https://www.junaidjamshed.com/black-dobby-embroidered-kurta-jss26654s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/2/6/26-654_1__1.jpg",
    brand: "Junaid Jamshed",
    price: 5490,
  },
  {
    name: "White Lawn Schiffli Co-Ord Set",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["White"],
    url: "https://www.junaidjamshed.com/white-lawn-schiffli-co-ord-set-jst262386s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/s/jst-26-2386s_1_.png",
    brand: "Junaid Jamshed",
    price: 7990,
  },
  {
    name: "Pink Raw Silk Embroidered Co-Ord Set",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Pink"],
    url: "https://www.junaidjamshed.com/pink-raw-silk-embroidered-co-ord-set-jps263997s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/p/jps-26-3997s_1_.jpg",
    brand: "Junaid Jamshed",
    price: 11990,
  },
  {
    name: "Purple Cotton Textured Co-Ord Set",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Purple"],
    url: "https://www.junaidjamshed.com/purple-cotton-textured-2pc-stitched-jst252217s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/s/jst-25-2217_1_.jpg",
    brand: "Junaid Jamshed",
    price: 4193,
  },
  {
    name: "Blue Dobby Embroidered Kurta",
    type: "Kurta",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://www.junaidjamshed.com/blue-dobby-embroidered-kurta-jss26657s.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/2/6/26-657_1_.jpg",
    brand: "Junaid Jamshed",
    price: 5490,
  },
  {
    name: "Embroidered Cotton Ice Blue 2PC",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://diners.com.pk/products/wkl2078-2pc-ice-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/WKL2078-2PC_3.jpg?v=1775200664",
    brand: "Diners",
    price: 6490,
  },
  {
    name: "Embroidered Jacquard Blue 2PC",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Blue"],
    url: "https://diners.com.pk/products/wk21411-2pc-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/WK21411-2PC_1_1.webp?v=1776144334",
    brand: "Diners",
    price: 6490,
  },
  {
    name: "Pink Embroidered 3PC Unstitched",
    type: "Shalwar Kameez",
    category: "Festive",
    gender: "Female",
    color: ["Pink"],
    url: "https://diners.com.pk/products/wu32039-pink",
    imageUrl: "https://diners.com.pk/cdn/shop/files/WU32039-PINK-01.webp?v=1749729726",
    brand: "Diners",
    price: 6392,
  },
  {
    name: "Khaddi Net Pink Kurti",
    type: "Kurta",
    category: "Festive",
    gender: "Female",
    color: ["Pink"],
    url: "https://diners.com.pk/products/women-stitched-kurti-71",
    imageUrl: "https://diners.com.pk/cdn/shop/products/WKL-1124-PINK-RS-8290-01_2000x.jpg?v=1686078387",
    brand: "Diners",
    price: 5790,
  },
  {
    name: "Embroidered Jacquard Green 2PC",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Green"],
    url: "https://diners.com.pk/products/wkl1934-2pc-bot-green",
    imageUrl: "https://diners.com.pk/cdn/shop/files/WKL1934-2PC_1.webp?v=1776144325",
    brand: "Diners",
    price: 6990,
  },
  {
    name: "White Dyed 2 Piece",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["White"],
    url: "https://bonanzasatrangi.com/products/wp2psbs26hr1f33",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/White-Dyed-2_Piece_WP2PSBS26HR1F33.jpg?v=1773380462&width=800",
    brand: "Bonanza Satrangi",
    price: 4893,
  },
  {
    name: "Black Dyed 2 Piece",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Female",
    color: ["Black"],
    url: "https://bonanzasatrangi.com/products/wp2psbs26hr2m46",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/WP2PSBS26HR2M46_bfc5378f-f200-4aa5-bfeb-3eb1c7a18ad2.jpg?v=1775114362&width=800",
    brand: "Bonanza Satrangi",
    price: 7290,
  },
  {
    name: "Rust Cotton Silk 2 Piece",
    type: "Shalwar Kameez",
    category: "Festive",
    gender: "Female",
    color: ["Brown"],
    url: "https://bonanzasatrangi.com/products/wps25se2023",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/Dress4_1_b3b4dd67-830e-485f-98e3-012a1c94d6c6.jpg?v=1756533024&width=800",
    brand: "Bonanza Satrangi",
    price: 7203,
  },
  {
    name: "Abaya - 5041",
    type: "Abaya",
    category: "Modest",
    gender: "Female",
    color: ["Black"],
    url: "https://zellbury.com/products/abaya-wmw25041",
    imageUrl: "https://zellbury.com/cdn/shop/files/WMW25041_BLACK_1.jpg?v=1772604258&width=823",
    brand: "Zellbury",
    price: 3290,
  },
  {
    name: "Tunics - 2042",
    type: "Frock",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://zellbury.com/products/tunics-wps2612042",
    imageUrl: "https://zellbury.com/cdn/shop/files/WPS2612042_3.jpg?v=1772624084&width=823",
    brand: "Zellbury",
    price: 2690,
  },
  {
    name: "Multicolor Viscose Yarn Dyed Saree",
    type: "Saree",
    category: "Formal",
    gender: "Female",
    color: ["Maroon"],
    url: "https://www.junaidjamshed.com/multicolor-viscose-yarn-dyed-saree-jsr-w-24-510.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/s/jsr-24-510_1_.jpg",
    brand: "Junaid Jamshed",
    price: 4495,
  },
  {
    name: "Brown Abaya",
    type: "Abaya",
    category: "Modest",
    gender: "Female",
    color: ["Brown"],
    url: "https://zellbury.com/products/abaya-wmw25037",
    imageUrl: "https://zellbury.com/cdn/shop/files/WMW25037_1.jpg?v=1772604259&width=990",
    brand: "Zellbury",
    price: 3290,
  },
  {
    name: "Pink Frock",
    type: "Frock",
    category: "Casual",
    gender: "Female",
    color: ["Pink"],
    url: "https://zellbury.com/products/tunics-wws251392",
    imageUrl: "https://zellbury.com/cdn/shop/files/WWS251392_5.jpg?v=1762177033&width=990",
    brand: "Zellbury",
    price: 2690,
  },
  {
    name: "Maroon Cotton 3 piece",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Red"],
    url: "https://bonanzasatrangi.com/products/wp3psfw25f11d1",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/WP3PSFW25F11D1.jpg",
    brand: "Bonanza Satrangi",
    price: 9093,
  },
  {
    name: "Sea Breeze 3 Piece",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Female",
    color: ["Blue"],
    url: "https://bonanzasatrangi.com/products/wus25de3029",
    imageUrl: "https://bonanzasatrangi.com/cdn/shop/files/WUS25DE3029_3.jpg",
    brand: "Bonanza Satrangi",
    price: 4495,
  },
  {
    name: "Brown Casual Kameez Shalwar",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Brown"],
    url: "https://www.junaidjamshed.com/brown-casual-kameez-shalwar-jjksa33809.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/j/jjks-33809_2_.jpg",
    brand: "Junaid Jamshed",
    price: 9490,
  },
  {
    name: "Pink Saree",
    type: "Saree",
    category: "Formal",
    gender: "Female",
    color: ["Pink"],
    url: "https://omalbykomal.com/products/maha-saree",
    imageUrl: "https://omalbykomal.com/cdn/shop/files/NRW01327.jpg",
    brand: "Omal by Komal",
    price: 9000,
  },
  {
    name: "Blue Casual Kurta Trouser",
    type: "Kurta",
    category: "Casual",
    gender: "Male",
    color: ["Blue"],
    url: "https://www.junaidjamshed.com/blue-casual-kurta-trouser-jjkpa33885.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/3/3/33885jjkp-11_1_.jpg",
    brand: "Junaid Jamshed",
    price: 8890,
  },
  {
    name: "Jade Shalwar Kameez",
    type: "Shalwar Kameez",
    category: "Casual",
    gender: "Male",
    color: ["Brown"],
    url: "https://zellbury.com/products/jade-shalwar-kameez-mskj2502605",
    imageUrl: "https://zellbury.com/cdn/shop/files/MSKJ2502605_7.jpg",
    brand: "Zellbury",
    price: 4490,
  },
  {
    name: "Teal Blue Casual Short Kurta Trousers",
    type: "Kurta",
    category: "Casual",
    gender: "Male",
    style: "short",
    color: ["Blue"],
    url: "https://www.junaidjamshed.com/teal-blue-casual-short-kurta-trousers-jjshkpa47708.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/4/7/47708jjshkp_3_.jpg",
    brand: "Junaid Jamshed",
    price: 8990,
  },
  {
    name: "Sky Blue Shalwar Kameez with Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://diners.com.pk/products/egw0020-sky-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/EGW0020-Sky-01_1200x.webp",
    brand: "Diners",
    price: 13194,
  },
  {
    name: "Dark Blue Shalwar Kameez with Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["Blue"],
    url: "https://diners.com.pk/products/egw0034-d-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/EGW-0034-D-BLUE-01_1200x.webp",
    brand: "Diners",
    price: 8994,
  },
  {
    name: "Navy Blue Wash & Wear Shalwar Kameez",
    type: "Kurta",
    category: "Formal",
    gender: "Male",
    color: ["Black"],
    url: "https://diners.com.pk/products/etks0034-n-blue",
    imageUrl: "https://diners.com.pk/cdn/shop/files/ETKS0034-N-BLUE-02_1200x.webp",
    brand: "Diners",
    price: 9594,
  },
  {
    name: "Black Plain Kameez Shalwar",
    type: "Kurta",
    category: "Casual",
    gender: "Male",
    color: ["Black"],
    url: "https://www.junaidjamshed.com/black-plain-kameez-shalwar-jjksa30778r47ap.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/3/0/30778_1__1_10.jpg",
    brand: "Junaid Jamshed",
    price: 6390,
  },
  {
    name: "Off White Kameez Shalwar with Waistcoat",
    type: "Shalwar Kameez",
    category: "Formal",
    gender: "Male",
    color: ["White"],
    hasWaistcoat: true,
    url: "https://www.junaidjamshed.com/off-white-exclusive-kameez-shalwar-waistcoat-jjksvca48338.html",
    imageUrl: "https://www.junaidjamshed.com/media/catalog/product/j/j/jjks-48286-sig_8_-_copy_-_copy_3.jpg?width=436&height=560&canvas=436,560&optimize=medium&bg-color=255,255,255&fit=bounds",
    brand: "Junaid Jamshed",
    price: 24990,
  },
  {
    name: "White Waistcoat",
    type: "Waistcoat",
    category: "Formal",
    gender: "Male",
    color: ["White"],
    url: "https://zellbury.com/products/waist-coat-mwc25105",
    imageUrl: "https://zellbury.com/cdn/shop/files/MWC25105_11.jpg",
    brand: "Zellbury",
    price: 3890,
  },
  {
    name: "Blue Blazer",
    type: "Blazer",
    category: "Formal",
    gender: "Male",
    color: ["Black","Blue"],
    url: "https://zellbury.com/products/blazer-mcbc2505",
    imageUrl: "https://zellbury.com/cdn/shop/files/MCBC2505_BLUE_4.jpg",
    brand: "Zellbury",
    price: 7990,
  }
];

// ================= SEED FUNCTION =================
async function seedDB() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("MongoDB connected");

    await Outfit.deleteMany(); // optional reset
    await Outfit.insertMany(outfits);

    console.log("Outfits seeded successfully");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedDB();